2024-05-27 14:15:40,556 INFO    MainThread:15279 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-05-27 14:15:40,557 INFO    MainThread:15279 [wandb_setup.py:_flush():76] Configure stats pid to 15279
2024-05-27 14:15:40,558 INFO    MainThread:15279 [wandb_setup.py:_flush():76] Loading settings from /home/test/.config/wandb/settings
2024-05-27 14:15:40,558 INFO    MainThread:15279 [wandb_setup.py:_flush():76] Loading settings from /home/test/FRL/wandb/settings
2024-05-27 14:15:40,558 INFO    MainThread:15279 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-27 14:15:40,558 INFO    MainThread:15279 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-27 14:15:40,558 INFO    MainThread:15279 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program_abspath': '/home/test/FRL/main.py', 'program': '/home/test/FRL/main.py'}
2024-05-27 14:15:40,559 INFO    MainThread:15279 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-27 14:15:40,559 INFO    MainThread:15279 [wandb_init.py:_log_setup():521] Logging user logs to /home/test/FRL/wandb/run-20240527_141540-eaepxfy0/logs/debug.log
2024-05-27 14:15:40,560 INFO    MainThread:15279 [wandb_init.py:_log_setup():522] Logging internal logs to /home/test/FRL/wandb/run-20240527_141540-eaepxfy0/logs/debug-internal.log
2024-05-27 14:15:40,560 INFO    MainThread:15279 [wandb_init.py:init():561] calling init triggers
2024-05-27 14:15:40,560 INFO    MainThread:15279 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {}
2024-05-27 14:15:40,561 INFO    MainThread:15279 [wandb_init.py:init():611] starting backend
2024-05-27 14:15:40,561 INFO    MainThread:15279 [wandb_init.py:init():615] setting up manager
2024-05-27 14:15:40,568 INFO    MainThread:15279 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-05-27 14:15:40,572 INFO    MainThread:15279 [wandb_init.py:init():623] backend started and connected
2024-05-27 14:15:40,578 INFO    MainThread:15279 [wandb_init.py:init():715] updated telemetry
2024-05-27 14:15:40,585 INFO    MainThread:15279 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-05-27 14:15:41,290 INFO    MainThread:15279 [wandb_run.py:_on_init():2357] communicating current version
2024-05-27 14:15:41,494 INFO    MainThread:15279 [wandb_run.py:_on_init():2366] got version response upgrade_message: "wandb version 0.17.0 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-05-27 14:15:41,494 INFO    MainThread:15279 [wandb_init.py:init():799] starting run threads in backend
2024-05-27 14:15:45,285 INFO    MainThread:15279 [wandb_run.py:_console_start():2335] atexit reg
2024-05-27 14:15:45,286 INFO    MainThread:15279 [wandb_run.py:_redirect():2190] redirect: wrap_raw
2024-05-27 14:15:45,286 INFO    MainThread:15279 [wandb_run.py:_redirect():2255] Wrapping output streams.
2024-05-27 14:15:45,286 INFO    MainThread:15279 [wandb_run.py:_redirect():2280] Redirects installed.
2024-05-27 14:15:45,287 INFO    MainThread:15279 [wandb_init.py:init():842] run started, returning control to user process
2024-05-27 14:15:46,777 INFO    MainThread:15279 [pyagent.py:run():324] Starting sweep agent: entity=None, project=None, count=400
2024-05-27 14:15:57,939 WARNING MsgRouterThr:15279 [router.py:message_loop():77] message_loop has been closed
2024-05-27 14:16:02,313 INFO    Thread-9 (_run_job):15279 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-05-27 14:16:02,313 INFO    Thread-9 (_run_job):15279 [wandb_setup.py:_flush():76] Configure stats pid to 15279
2024-05-27 14:16:02,314 INFO    Thread-9 (_run_job):15279 [wandb_setup.py:_flush():76] Loading settings from /home/test/.config/wandb/settings
2024-05-27 14:16:02,314 INFO    Thread-9 (_run_job):15279 [wandb_setup.py:_flush():76] Loading settings from /home/test/FRL/wandb/settings
2024-05-27 14:16:02,314 INFO    Thread-9 (_run_job):15279 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'different-k-mnist-attack-0.1', 'entity': 'griffith', 'root_dir': '/home/test/FRL', 'sweep_id': 'dr0tv8jb', 'run_id': '1qp4ubi7', 'sweep_param_path': '/home/test/FRL/wandb/sweep-dr0tv8jb/config-1qp4ubi7.yaml'}
2024-05-27 14:16:02,314 INFO    Thread-9 (_run_job):15279 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-27 14:16:02,314 INFO    Thread-9 (_run_job):15279 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program_abspath': '/home/test/FRL/main.py', 'program': '/home/test/FRL/main.py'}
2024-05-27 14:16:02,314 INFO    Thread-9 (_run_job):15279 [wandb_init.py:_log_setup():521] Logging user logs to /home/test/FRL/wandb/run-20240527_141602-1qp4ubi7/logs/debug.log
2024-05-27 14:16:02,314 INFO    Thread-9 (_run_job):15279 [wandb_init.py:_log_setup():522] Logging internal logs to /home/test/FRL/wandb/run-20240527_141602-1qp4ubi7/logs/debug-internal.log
2024-05-27 14:16:02,314 INFO    Thread-9 (_run_job):15279 [wandb_init.py:init():561] calling init triggers
2024-05-27 14:16:02,315 INFO    Thread-9 (_run_job):15279 [wandb_init.py:init():568] wandb.init called with sweep_config: {'iteration': 50, 'k': 0, 'lr': 0.001, 'm_r': 0, 'max_t': 1000, 'nep': 100, 'noise': 1, 'temp': 0.1}
config: {}
2024-05-27 14:16:02,315 INFO    Thread-9 (_run_job):15279 [wandb_init.py:init():606] wandb.init() called when a run is still active
2024-05-27 14:16:02,409 ERROR   Thread-9 (_run_job):15279 [wandb_init.py:init():1209] error
Traceback (most recent call last):
  File "/home/test/anaconda3/envs/FRL_test/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1181, in init
    run = wi.init()
  File "/home/test/anaconda3/envs/FRL_test/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 607, in init
    with telemetry.context() as tel:
  File "/home/test/anaconda3/envs/FRL_test/lib/python3.10/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/test/anaconda3/envs/FRL_test/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 763, in _telemetry_callback
    self._telemetry_flush()
  File "/home/test/anaconda3/envs/FRL_test/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 774, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/test/anaconda3/envs/FRL_test/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 101, in _publish_telemetry
    self._publish(rec)
  File "/home/test/anaconda3/envs/FRL_test/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/test/anaconda3/envs/FRL_test/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 221, in send_record_publish
    self.send_server_request(server_req)
  File "/home/test/anaconda3/envs/FRL_test/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home/test/anaconda3/envs/FRL_test/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/test/anaconda3/envs/FRL_test/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
